-- CREATE DATABASE library;
/*USE library;
CREATE TABLE katalogs (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NAME VARCHAR(255) NOT NULL,
author INT NOT NULL,
YEAR DATE NOT NULL,
availability INT NOT NULL DEFAULT 1,
FOREIGN KEY (author) REFERENCES authors(id)
)

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
email VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ROLE BOOLEAN NOT NULL )
*/
-- UPDATE users SET ROLE = 1 WHERE id = 1;